### ISSUE TITLE
Banner content Overflow

### ISSUE THREAD

**Issue by AbhishekJupalli-1409** [AbhishekJupalli-1409/Netflixclone2#1]
### Banner content is overflowing in the small screens and tablets.

![image](https://github.com/user-attachments/assets/c3fd997d-9d96-443b-940f-44d1e73123ee)

**Comment by linuxlinux0009** [comment]
I want to work on this Issue

**Comment by AbhishekJupalli-1409** [comment]
Issue solved by me
